[mypy]
python_version = 3.11
ignore_missing_imports = true
disable_error_code =
    attr-defined,
    assignment,
    arg-type,
    call-arg,
    index,
    import-untyped,
    operator,
    return,
    return-value,
    union-attr,
    var-annotated
namespace_packages = true
explicit_package_bases = true
